nguage: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/
branches:
  only:
    - master
    - production